algoritmo "creuza02"
var
dolar, reais : real
inicio
      escreval("Preciso viajar la pra Zoropa, quantos Dolares sera ")
      escreval("que eu consigo comprar ?")
      escreval
      escreval("Deixa eu ver aqui, quantos reais eu tenho ?")
      leia (reais)
      dolar <- int (reais/3.84)

      escreval
      escreval("Então viado, por essa cotação da pra comprar ", dolar," dolares")
      escreval

      escreval("AHAZEI VIADO!!!")
fimalgoritmo